TEXTS = {
    "ru": {
        "welcome": "🛡 Alumix\n\nℹ️ Безопасный гарант для сделок в Telegram.\n\nЧто внутри:\n• защита от мошенников\n• удержание средств до завершения сделки\n• история и статусы сделок\n• поддержка через @AlumixHelper\n\nВыберите действие ниже.",
        "create_deal": "🟢 Создать сделку",
        "change_lang": "🌐 Сменить язык",
        "credentials": "💳 Реквизиты",
        "support": "🆘 Поддержка",
        "about": "ℹ️ О сервисе",
        "admin_panel": "⚙️ Админ панель",
        "back": "◀️ Назад",
        "send_gift_link": "🎁 Отправьте ссылку на NFT Gift\n\nМожно указать одну или несколько ссылок, например:\nhttps://t.me/nft/DurovsCap-1",
        "choose_payment": "👝 Выберите способ оплаты",
        "enter_amount": "💰 Введите сумму сделки",
        "enter_card": "🏦 Введите номер карты\n\nНа нее будет отправлена оплата после завершения сделки.",
        "enter_stars_username": "👤 Введите юзернейм для получения Stars\n\nНапример: @username",
        "enter_crypto_wallet": "🪙 Введите адрес крипто кошелька",
        "deal_created": "✅ Сделка создана!\n\n📋 Номер: {deal_number}\n\n📝 Описание: {gift_link}\n💰 Сумма: {amount} {currency}\n💳 Реквизиты: {details}\n\n🔗 Ссылка для покупателя:\nhttps://t.me/{bot_username}?start={deal_number}",
        "buyer_welcome": "🛡 Alumix — Гарант сделки\n\n🎁 Подарок: {gift_link}\n💰 Сумма: {amount} {currency}\n👤 Продавец: @{seller_username}",
        "join_deal": "✅ Присоединиться",
        "buyer_joined": "🎉 Покупатель @{buyer_username} присоединился к сделке!\n\nУспешных сделок: {successful_deals}",
        "admin_paid": "💸 Покупатель успешно произвел оплату, отправьте подарок!",
        "confirm_gift_received": "🎁 Я получил подарок, отправить деньги",
        "deal_completed": "✅ Сделка завершена! Средства отправлены продавцу.",
        "about_text": "ℹ️ F.A.Q - Часто задаваемые вопросы\n\n1. Что делает бот?\n🤖 Бот работает как автоматический сервис-гарант: обеспечивает безопасный обмен NFT-подарками, Telegram-каналами, чатами, кодами ботов и другими цифровыми товарами.\n\n2. Что можно купить или продать?\n📦 Почти что угодно - от цифровых активов до кодов, подписок и Telegram-ресурсов.\n\n3. Как работает сделка?\n🧭 Все транзакции автоматизированы: бот удерживает товар и оплату, затем переводит средства и активы после подтверждения обеими сторонами.\n\n4. Как вывести средства?\n👝 Вывод доступен в любой удобной валюте.\n\n5. Есть ли поддержка?\n📢 Да! Поддержка доступна 24/7 и поможет с любыми вопросами.\n\n6. Это безопасно?\n🛡 Да, бот использует автоматическую систему гаранта, исключающую риск мошенничества.",
        "credentials_menu": "💳 Управление реквизитами\n\n👤 Stars: {stars}\n🏦 Карта: {card}\n🪙 USDT: {usdt}\n🪙 TON: {ton}",
        "edit_stars": "✏️ Stars username",
        "edit_card": "✏️ Номер карты",
        "edit_usdt": "✏️ USDT кошелёк",
        "edit_ton": "✏️ TON кошелёк",
        "saved": "✅ Сохранено!",
        "language_changed": "🌐 Язык изменён на русский.",
        "choose_language": "🌐 Выберите язык / Choose language",
        "usdt_btn": "🪙 USDT",
        "ton_btn": "💎 TON (Gram)",
        "rub_btn": "🇷🇺 Рубли",
        "stars_btn": "⭐ Telegram Stars",
        "admin_deals_list": "📋 Список сделок:",
        "confirm_payment_btn": "✅ Оплатить сделку {deal_number}",
        "admin_add": "➕ Добавить админа",
        "admin_remove": "➖ Удалить админа",
        "admin_list": "👥 Список админов",
        "enter_admin_id": "🆔 Введите Telegram ID нового администратора",
        "enter_admin_remove_id": "🆔 Введите ID администратора для удаления",
        "admin_added": "✅ Администратор добавлен!",
        "admin_removed": "✅ Администратор удалён!",
        "invalid_link": "❌ Неверная ссылка. Пришлите ссылку в формате https://t.me/...",
        "invalid_amount": "❌ Введите корректную сумму (число)",
        "cancel": "❌ Отмена",
        "cancelled": "❌ Действие отменено.",
    },
    "en": {
        "welcome": "🛡 Alumix\n\nℹ️ Safe escrow for Telegram deals.\n\nFeatures:\n• Fraud protection\n• Funds held until deal completion\n• Deal history & statuses\n• Support via @AlumixHelper\n\nChoose an action below.",
        "create_deal": "🟢 Create deal",
        "change_lang": "🌐 Change language",
        "credentials": "💳 Credentials",
        "support": "🆘 Support",
        "about": "ℹ️ About",
        "admin_panel": "⚙️ Admin panel",
        "back": "◀️ Back",
        "send_gift_link": "🎁 Send NFT Gift link\n\nYou can send one or several links, e.g.:\nhttps://t.me/nft/DurovsCap-1",
        "choose_payment": "👝 Choose payment method",
        "enter_amount": "💰 Enter deal amount",
        "enter_card": "🏦 Enter card number\n\nPayment will be sent here after the deal.",
        "enter_stars_username": "👤 Enter Stars username\n\nExample: @username",
        "enter_crypto_wallet": "🪙 Enter crypto wallet address",
        "deal_created": "✅ Deal created!\n\n📋 Number: {deal_number}\n\n📝 Description: {gift_link}\n💰 Amount: {amount} {currency}\n💳 Details: {details}\n\n🔗 Buyer link:\nhttps://t.me/{bot_username}?start={deal_number}",
        "buyer_welcome": "🛡 Alumix — Deal Escrow\n\n🎁 Gift: {gift_link}\n💰 Amount: {amount} {currency}\n👤 Seller: @{seller_username}",
        "join_deal": "✅ Join",
        "buyer_joined": "🎉 Buyer @{buyer_username} joined the deal!\n\nSuccessful deals: {successful_deals}",
        "admin_paid": "💸 Buyer paid successfully, send the gift!",
        "confirm_gift_received": "🎁 I received the gift, release funds",
        "deal_completed": "✅ Deal completed! Funds sent to seller.",
        "about_text": "ℹ️ F.A.Q\n\n1. What does the bot do?\n🤖 Acts as automatic escrow: secure exchange of NFT gifts, channels, chats, bots and digital goods.\n\n2. What can be traded?\n📦 Almost anything - digital assets, codes, subscriptions, Telegram resources.\n\n3. How does a deal work?\n🧭 Fully automated: bot holds goods & payment, releases them after both sides confirm.\n\n4. How to withdraw?\n👝 Withdrawal in any currency.\n\n5. Support?\n📢 Yes! 24/7 support for any questions.\n\n6. Is it safe?\n🛡 Yes, automatic escrow eliminates fraud risk.",
        "credentials_menu": "💳 Manage credentials\n\n👤 Stars: {stars}\n🏦 Card: {card}\n🪙 USDT: {usdt}\n🪙 TON: {ton}",
        "edit_stars": "✏️ Stars username",
        "edit_card": "✏️ Card number",
        "edit_usdt": "✏️ USDT wallet",
        "edit_ton": "✏️ TON wallet",
        "saved": "✅ Saved!",
        "language_changed": "🌐 Language changed to English.",
        "choose_language": "🌐 Выберите язык / Choose language",
        "usdt_btn": "🪙 USDT",
        "ton_btn": "💎 TON (Gram)",
        "rub_btn": "🇷🇺 Rubles",
        "stars_btn": "⭐ Telegram Stars",
        "admin_deals_list": "📋 Deals list:",
        "confirm_payment_btn": "✅ Confirm deal {deal_number}",
        "admin_add": "➕ Add admin",
        "admin_remove": "➖ Remove admin",
        "admin_list": "👥 Admin list",
        "enter_admin_id": "🆔 Enter Telegram ID of new admin",
        "enter_admin_remove_id": "🆔 Enter ID of admin to remove",
        "admin_added": "✅ Admin added!",
        "admin_removed": "✅ Admin removed!",
        "invalid_link": "❌ Invalid link. Send link in format https://t.me/...",
        "invalid_amount": "❌ Enter valid amount (number)",
        "cancel": "❌ Cancel",
        "cancelled": "❌ Cancelled.",
    }
}

def t(lang, key, **kwargs):
    text = TEXTS.get(lang, TEXTS["ru"]).get(key, key)
    return text.format(**kwargs) if kwargs else text