TEXTS = {
    "ru": {
        "welcome": "🛡 <b>Alumix</b> — безопасный гарант сделок в Telegram.\n\nℹ️ Мы защищаем ваши сделки от мошенничества.\n\nВыберите действие:",
        "create_deal": "🟢 Создать сделку",
        "balance_btn": "💰 Баланс",
        "change_lang": "🌐 Сменить язык",
        "credentials": "💳 Реквизиты",
        "support": "🆘 Поддержка",
        "about": "ℹ️ О сервисе",
        "admin_panel": "⚙️ Админ панель",
        "back": "Назад",
        "cancel": "Отмена",
        "send_gift_link": "🎁 Отправьте ссылку на NFT Gift\n\nПример: https://t.me/nft/DurovsCap-1",
        "invalid_link": "❌ Неверная ссылка. Ссылка должна начинаться с https://t.me/",
        "choose_payment": "💳 Выберите способ оплаты:",
        "usdt_btn": "💵 USDT",
        "ton_btn": "💎 TON",
        "rub_btn": "💳 Рубли",
        "sbp_btn": "🏦 СБП",
        "uah_btn": "🇺🇦 Гривны",
        "stars_btn": "⭐ Stars",
        "enter_amount": "💰 Введите сумму сделки:",
        "invalid_amount": "❌ Введите корректную сумму (число больше 0)",
        "enter_card": "🏦 Введите номер карты\n\nНа нее будет отправлена оплата после завершения сделки.",
        "enter_sbp_phone": "📱 Введите номер телефона для СБП\n\nНа этот номер придут деньги после завершения сделки.\nПример: +79991234567",
        "enter_uah_card": "🏦 Введите номер украинской карты\n\nНа нее будет отправлена оплата после завершения сделки.\nПример: 5168 XXXX XXXX XXXX",
        "enter_stars_username": "⭐ Введите ваш @username для Stars",
        "enter_crypto_wallet": "💎 Введите адрес кошелька (USDT TRC20 / TON)",
        "deal_created": "✅ Сделка создана!\n\n📋 Номер: {deal_number}\n🎁 Подарок: {gift_link}\n💰 Сумма: {amount} {currency}\n💳 Реквизиты: {details}\n\n🔗 Ссылка для покупателя:\nhttps://t.me/{bot_username}?start={deal_number}",
        "buyer_welcome": "🛡 Сделка #{deal_number}\n\n🎁 Подарок: {gift_link}\n💰 Сумма: {amount} {currency}\n👤 Продавец: @{seller_username}\n\nНажмите кнопку, чтобы присоединиться к сделке.",
        "buyer_joined": "👀 Покупатель @{buyer_username} присоединился к сделке!\n\n⭐ Успешных сделок у покупателя: {successful_deals}\n\n⏳ Ожидайте оплату.",
        "join_deal": "🤝 Присоединиться к сделке",
        "confirm_gift": "✅ Я получил подарок",
        "about_text": "ℹ️ <b>Alumix</b> — гарант-сервис для безопасных сделок с NFT Gift в Telegram.\n\n🛡 Как это работает:\n1. Продавец создаёт сделку и получает ссылку\n2. Покупатель присоединяется по ссылке\n3. Администратор подтверждает оплату\n4. Продавец отправляет подарок\n5. Покупатель подтверждает получение\n\n💰 Комиссия сервиса включена в сумму сделки.\n🆘 Поддержка: @alumixHelp",
        "language_changed": "✅ Язык изменён / Language changed",
        "saved": "✅ Сохранено!",
        "cancelled": "❌ Действие отменено.",
        "credentials_menu": "💳 Ваши реквизиты:\n\n💳 Карта (RUB): {card}\n📱 СБП: {sbp}\n🇺🇦 Карта (UAH): {uah}\n⭐ Stars: {stars}\n💵 USDT: {usdt}\n💎 TON: {ton}",
        "enter_admin_id": "🆔 Введите Telegram ID администратора для добавления:",
        "enter_admin_remove_id": "🆔 Введите Telegram ID администратора для удаления:",
        "admin_added": "✅ Администратор добавлен!",
        "admin_removed": "✅ Администратор удалён!",
        "admin_deals_list": "📋 Список сделок:",
    },
    "en": {
        "welcome": "🛡 <b>Alumix</b> — safe deal guarantor in Telegram.\n\nℹ️ We protect your deals from fraud.\n\nChoose an action:",
        "create_deal": "🟢 Create deal",
        "balance_btn": "💰 Balance",
        "change_lang": "🌐 Change language",
        "credentials": "💳 Credentials",
        "support": "🆘 Support",
        "about": "ℹ️ About",
        "admin_panel": "⚙️ Admin panel",
        "back": "Back",
        "cancel": "Cancel",
        "send_gift_link": "🎁 Send the NFT Gift link\n\nExample: https://t.me/nft/DurovsCap-1",
        "invalid_link": "❌ Invalid link. The link must start with https://t.me/",
        "choose_payment": "💳 Choose payment method:",
        "usdt_btn": "💵 USDT",
        "ton_btn": "💎 TON",
        "rub_btn": "💳 Rubles",
        "sbp_btn": "🏦 SBP",
        "uah_btn": "🇺🇦 Hryvnia",
        "stars_btn": "⭐ Stars",
        "enter_amount": "💰 Enter the deal amount:",
        "invalid_amount": "❌ Enter a valid amount (number greater than 0)",
        "enter_card": "🏦 Enter your card number\n\nPayment will be sent here after the deal.",
        "enter_sbp_phone": "📱 Enter phone number for SBP\n\nMoney will be sent to this number after the deal.\nExample: +79991234567",
        "enter_uah_card": "🏦 Enter your Ukrainian card number\n\nPayment will be sent here after the deal.\nExample: 5168 XXXX XXXX XXXX",
        "enter_stars_username": "⭐ Enter your @username for Stars",
        "enter_crypto_wallet": "💎 Enter wallet address (USDT TRC20 / TON)",
        "deal_created": "✅ Deal created!\n\n📋 Number: {deal_number}\n🎁 Gift: {gift_link}\n💰 Amount: {amount} {currency}\n💳 Details: {details}\n\n🔗 Buyer link:\nhttps://t.me/{bot_username}?start={deal_number}",
        "buyer_welcome": "🛡 Deal #{deal_number}\n\n🎁 Gift: {gift_link}\n💰 Amount: {amount} {currency}\n👤 Seller: @{seller_username}\n\nPress the button to join the deal.",
        "buyer_joined": "👀 Buyer @{buyer_username} joined the deal!\n\n⭐ Buyer successful deals: {successful_deals}\n\n⏳ Waiting for payment.",
        "join_deal": "🤝 Join deal",
        "confirm_gift": "✅ I received the gift",
        "about_text": "ℹ️ <b>Alumix</b> — guarantor service for safe NFT Gift deals in Telegram.\n\n🛡 How it works:\n1. Seller creates a deal and gets a link\n2. Buyer joins via the link\n3. Admin confirms payment\n4. Seller sends the gift\n5. Buyer confirms receipt\n\n💰 Service fee is included in the deal amount.\n🆘 Support: @alumixHelp",
        "language_changed": "✅ Language changed / Язык изменён",
        "saved": "✅ Saved!",
        "cancelled": "❌ Action cancelled.",
        "credentials_menu": "💳 Your credentials:\n\n💳 Card (RUB): {card}\n📱 SBP: {sbp}\n🇺🇦 Card (UAH): {uah}\n⭐ Stars: {stars}\n💵 USDT: {usdt}\n💎 TON: {ton}",
        "enter_admin_id": "🆔 Enter Telegram ID of the admin to add:",
        "enter_admin_remove_id": "🆔 Enter Telegram ID of the admin to remove:",
        "admin_added": "✅ Admin added!",
        "admin_removed": "✅ Admin removed!",
        "admin_deals_list": "📋 Deals list:",
    },
}


def t(lang, key, **kwargs):
    text = TEXTS.get(lang, TEXTS["ru"]).get(key) or TEXTS["ru"].get(key, key)
    if kwargs:
        text = text.format(**kwargs)
    return text